//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindLosts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LostsEntries
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Code { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPhone { get; set; }
        public Nullable<System.DateTime> LostDate { get; set; }
        public string LostPlace { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
